version: '3.8'

services:
  # 1. Le Frontend (Interface React)
  frontend:
    build: ./frontend/VACOP-app
    container_name: vacop_frontend
    ports:
      - "80:80"  # Accessible via http://localhost
    depends_on:
      - backend
    networks:
      - vacop_net

  # 2. Le Backend (API Flask)
  backend:
    build: ./backend/vacop-backend
    container_name: vacop_backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://vacop_user:vacop_pass@db:5432/vacop_db
      - SECRET_KEY=dev_secret_key_change_me

      # MQTT: inside docker, use the service name "mqtt" and port 1883
      - MQTT_BROKER_URL=neocampus.univ-tlse3.fr
      - MQTT_BROKER_PORT=10883

      # Optional but recommended to keep topics consistent
      - MQTT_TOPIC=TestTopic/VACOP/localisation/gnss
      - MQTT_COMMAND_BASE=TestTopic/VACOP/command

      # If your local mosquitto has no auth, leave empty or omit these
      - MQTT_USERNAME=test
      - MQTT_PASSWORD=test
      - MQTT_CLIENT_ID=vacop_backend
    depends_on:
      - db
      - mqtt
    networks:
      - vacop_net


  # 3. La Base de données (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: vacop_db
    environment:
      - POSTGRES_USER=vacop_user
      - POSTGRES_PASSWORD=vacop_pass
      - POSTGRES_DB=vacop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vacop_net

  # 4. Le Broker MQTT (Communication Véhicule)
  mqtt:
    image: eclipse-mosquitto:1.6
    container_name: vacop_mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - vacop_net

  # 5. Le Serveur de Flux Vidéo (MediaMTX)
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: vacop_mediamtx
    network_mode: "host"
    ports:
      - "8889:8889"     # WebRTC :  Dashboard React
      - "8189:8189/udp" # ICE : Pour que le flux passe à travers les firewalls
      - "5001:5001/udp" # Entrée : Pour que le code OpenCV envoie les images
    environment:
      - MTX_HLS=no
      - MTX_WEBRTC=yes
      - MTX_PATHS_ROBOT_SOURCE=udp://:5001

  # 6. Service de découverte automatique 
  discovery:
    image: python:3.9-slim
    container_name: vacop_discovery
    network_mode: "host"
    environment:
      - MQTT_BROKER_URL=neocampus.univ-tlse3.fr
      - MQTT_BROKER_PORT=10883
      - MQTT_USERNAME=test
      - MQTT_PASSWORD=test
    volumes:
      - ./discovery.py:/app/discovery.py
    working_dir: /app
    command: 
      sh -c "apt-get update && apt-get install -y openssh-client 
      && pip install paho-mqtt 
      && python3 discovery.py"
    restart: on-failure


networks:
  vacop_net:

volumes:
  postgres_data:
